# -*- coding: utf-8 -*-
"""checkpointing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/107OjQqajwM-R5qOjHh0f5Rx2kTxlYdqi
"""

import torch
import os
import json
import matplotlib.pyplot as plt

def save_checkpoint(model, optimizer, epoch, history, path="checkpoint.pt"):
    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'history': history
    }
    torch.save(checkpoint, path)

    # Save a JSON copy of history for easy reading/plotting later
    with open(path.replace(".pt", "_history.json"), "w") as f:
        json.dump(history, f)
    print(f"Checkpointed at epoch {epoch}")

def load_checkpoint(path, model, optimizer):
    if os.path.exists(path):
        print(f"Loading checkpoint: {path}")
        checkpoint = torch.load(path, map_location='cpu')
        model.load_state_dict(checkpoint['model_state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
        return checkpoint['epoch'] + 1, checkpoint['history']
    return 0, []

def plot_history(history):
    epochs = [h['epoch'] for h in history]
    t_loss = [h['train_loss'] for h in history]
    v_loss = [h['val_loss'] for h in history]

    plt.figure(figsize=(8, 5))
    plt.plot(epochs, t_loss, label='Train')
    plt.plot(epochs, v_loss, label='Val')
    plt.title('Training Progress (Masked L1 Loss)')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.show()