# -*- coding: utf-8 -*-
"""cnn_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t82ff7QzzA2uUIYkDQjKK0l7_1Njj6-q
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class MultiResBlock(nn.Module):
    """
    Multi-Resolution Block: Captures audio features at different scales
    (fine detail vs. broad harmonic structure) using parallel convolutions.
    """
    def __init__(self, in_channels, out_channels):
        super().__init__()
        unit = out_channels // 4

        # Parallel paths with different kernel sizes
        self.conv_3x3 = nn.Conv2d(in_channels, unit, kernel_size=3, padding=1)
        self.conv_5x5 = nn.Conv2d(in_channels, unit, kernel_size=5, padding=2)
        self.conv_7x7 = nn.Conv2d(in_channels, unit, kernel_size=7, padding=3)

        # 1x1 path to preserve residual information and match channel count
        self.conv_1x1 = nn.Conv2d(in_channels, out_channels - (unit*3), kernel_size=1)

        self.batch_norm = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        out1 = self.conv_3x3(x)
        out2 = self.conv_5x5(x)
        out3 = self.conv_7x7(x)
        out4 = self.conv_1x1(x)

        # Combine all resolutions
        out = torch.cat([out1, out2, out3, out4], dim=1)
        return self.relu(self.batch_norm(out))

class PolimiCNNAutoencoder(nn.Module):
    """
    Phase 3 Baseline: A Multi-Resolution CNN Autoencoder.
    NOTE: No skip connections are used to ensure this remains a baseline
    comparison for the Phase 2 U-Net.
    """
    def __init__(self):
        super().__init__()

        # Encoder: Downsampling the spectrogram
        self.enc1 = MultiResBlock(2, 32)   # Input: [Masked_Spec, Mask]
        self.pool1 = nn.MaxPool2d(2)       # 128 -> 64

        self.enc2 = MultiResBlock(32, 64)
        self.pool2 = nn.MaxPool2d(2)       # 64 -> 32

        self.enc3 = MultiResBlock(64, 128)
        self.pool3 = nn.MaxPool2d(2)       # 32 -> 16

        # Bottleneck: The compressed musical representation
        self.bottleneck = MultiResBlock(128, 256)

        # Decoder: Upsampling back to the original size
        self.up1 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.dec1 = MultiResBlock(256, 128)

        self.up2 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.dec2 = MultiResBlock(128, 64)

        self.up3 = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
        self.dec3 = MultiResBlock(64, 32)

        # Final Output Layer (Back to 1 channel: the reconstructed spectrogram)
        self.final_conv = nn.Conv2d(32, 1, kernel_size=1)

    def forward(self, x, mask):
        # x shape: (B, 1, 128, T) | mask shape: (B, 1, 128, T)
        # Concatenate spec and mask into a 2-channel input
        combined_input = torch.cat([x, mask], dim=1)

        # Encoder
        e1 = self.enc1(combined_input)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))

        # Bottleneck
        b = self.bottleneck(self.pool3(e3))

        # Decoder
        d1 = self.dec1(self.up1(b))
        d2 = self.dec2(self.up2(d1))
        d3 = self.dec3(self.up3(d2))

        out = self.final_conv(d3)

        # Final safety check: ensure output dimensions match input exactly
        if out.shape != x.shape:
            out = F.interpolate(out, size=(x.shape[2], x.shape[3]), mode='bilinear', align_corners=True)

        return out