# -*- coding: utf-8 -*-
"""train_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXe3mTBp8V4_wniPxodfciFef4_fq3fB
"""

import torch
from tqdm import tqdm

def masked_l1_loss(pred, target, mask):
    """
    Calculates L1 loss only on the missing/masked region of the audio.
    If mask value is 0 for the 'gap', then (1 - mask) isolates that gap.
    """
    gap_mask = 1.0 - mask
    loss = torch.abs(pred - target)
    # Average the error only over the gap pixels
    return torch.sum(loss * gap_mask) / (torch.sum(gap_mask) + 1e-8)

def train_one_epoch(model, dataloader, optimizer, device):
    model.train()
    total_loss = 0
    pbar = tqdm(dataloader, desc="Training")

    for batch in pbar:
        x, y, mask = batch["x"].to(device), batch["y"].to(device), batch["mask"].to(device)

        optimizer.zero_grad()
        output = model(x, mask)
        loss = masked_l1_loss(output, y, mask)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        pbar.set_postfix({"loss": f"{loss.item():.4f}"})

    return total_loss / len(dataloader)

def validate(model, dataloader, device):
    model.eval()
    total_loss = 0
    with torch.no_grad():
        for batch in dataloader:
            x, y, mask = batch["x"].to(device), batch["y"].to(device), batch["mask"].to(device)
            output = model(x, mask)
            loss = masked_l1_loss(output, y, mask)
            total_loss += loss.item()

    return total_loss / len(dataloader)